/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import static java.lang.Math.abs;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Dell
 */
public class Home_payment extends javax.swing.JFrame {

    /**
     * Creates new form Home_payment
     */
    public Home_payment() {
        initComponents();
    }
    
    PreparedStatement pst;
    public static Connection connect() {
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/minorproject1", "root","Diksha@1503");
            System.out.println("Connection done successfully");
        }
        catch (ClassNotFoundException ex)
        {
            ex.printStackTrace();

        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
        }
        return con;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timePicker1 = new com.raven.swing.TimePicker();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtexitTime = new javax.swing.JTextField();
        DisplayAmountBtn = new javax.swing.JPanel();
        displayAmount = new javax.swing.JLabel();
        txtcarplateno2 = new javax.swing.JTextField();
        setTimebtn = new javax.swing.JLabel();
        hourchooser = new javax.swing.JComboBox<>();
        minutechooser = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(555, 460));
        setMinimumSize(new java.awt.Dimension(555, 460));

        jPanel1.setBackground(new java.awt.Color(5, 2, 29));
        jPanel1.setMaximumSize(new java.awt.Dimension(555, 460));
        jPanel1.setMinimumSize(new java.awt.Dimension(555, 460));
        jPanel1.setPreferredSize(new java.awt.Dimension(555, 460));

        jPanel3.setBackground(new java.awt.Color(53, 53, 164));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bill");

        jLabel9.setBackground(new java.awt.Color(17, 12, 58));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel9.setText("< Back");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(160, 160, 160)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_rupee_96px.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Car Plate no.");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Exit Time");

        txtexitTime.setBackground(new java.awt.Color(5, 2, 29));
        txtexitTime.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtexitTime.setForeground(new java.awt.Color(255, 255, 204));
        txtexitTime.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtexitTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 12, 58), 2));
        txtexitTime.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtexitTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexitTimeActionPerformed(evt);
            }
        });

        DisplayAmountBtn.setBackground(new java.awt.Color(53, 53, 164));
        DisplayAmountBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 10, 41)));
        DisplayAmountBtn.setForeground(new java.awt.Color(255, 255, 204));
        DisplayAmountBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DisplayAmountBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DisplayAmountBtnMousePressed(evt);
            }
        });

        displayAmount.setBackground(new java.awt.Color(17, 12, 58));
        displayAmount.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        displayAmount.setForeground(new java.awt.Color(255, 255, 204));
        displayAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayAmount.setText("Display amount");
        displayAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                displayAmountMousePressed(evt);
            }
        });

        javax.swing.GroupLayout DisplayAmountBtnLayout = new javax.swing.GroupLayout(DisplayAmountBtn);
        DisplayAmountBtn.setLayout(DisplayAmountBtnLayout);
        DisplayAmountBtnLayout.setHorizontalGroup(
            DisplayAmountBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );
        DisplayAmountBtnLayout.setVerticalGroup(
            DisplayAmountBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        txtcarplateno2.setBackground(new java.awt.Color(5, 2, 29));
        txtcarplateno2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtcarplateno2.setForeground(new java.awt.Color(255, 255, 204));
        txtcarplateno2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtcarplateno2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 12, 58), 2));
        txtcarplateno2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        setTimebtn.setBackground(new java.awt.Color(153, 153, 255));
        setTimebtn.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        setTimebtn.setForeground(new java.awt.Color(255, 255, 204));
        setTimebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setTimebtn.setText("Set Time");
        setTimebtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 12, 58), 2));
        setTimebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                setTimebtnMousePressed(evt);
            }
        });

        hourchooser.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        hourchooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " " }));
        hourchooser.setBorder(null);
        hourchooser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hourchooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourchooserActionPerformed(evt);
            }
        });

        minutechooser.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        minutechooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        minutechooser.setBorder(null);
        minutechooser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hourchooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(setTimebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcarplateno2)
                            .addComponent(txtexitTime))
                        .addGap(107, 107, 107))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(DisplayAmountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcarplateno2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtexitTime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourchooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setTimebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(DisplayAmountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed

        new Home().show();
    }//GEN-LAST:event_jLabel9MousePressed

    private void displayAmountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayAmountMousePressed
        String ExitTime,carplateno,Entrytime = "";
        //id = txtid.getText();
        ExitTime = txtexitTime.getText();
        carplateno = txtcarplateno2.getText();
        //int c = Integer.parseInt(carplateno);

        try {
            String query = "update UserDetails set ExitTime ='"+ExitTime+"' where carplateno ='"+carplateno+"'";
            pst = Home_bookslot.connect().prepareStatement(query);
            pst.execute(query);
        
        
            String query2 = "select EntryTime from UserDetails where CarPlateNo ='"+carplateno+"'";
            pst = Home_bookslot.connect().prepareStatement(query2);
            ResultSet rs1 = pst.executeQuery(query2);
            ResultSetMetaData rsmd = rs1.getMetaData();
            while(rs1.next()){
                Entrytime = rs1.getString("EntryTime");
            }
        
        
        
            //EntryTime = 14:10  ExitTime = 15:30
        
            
            //calculate entry hour
            String entryh = Entrytime.substring(0, 2);
            int Entryhour = Integer.parseInt(entryh);
            //calculate exit hour
            String exith = ExitTime.substring(0,2);
            int Exithour = Integer.parseInt(exith);
            //caculate entry minutes
            String entrym = Entrytime.substring(3);
            int Entrymin = Integer.parseInt(entrym);
            //caculate exit minutes
            String exitm = ExitTime.substring(3);
            int Exitmin = Integer.parseInt(exitm);
        
            int totalEntrymin = (Entryhour*60)+Entrymin;
            int totalExitmin = (Exithour*60)+Exitmin;
        
            float totalTimeSpan = totalExitmin - totalEntrymin;
        
            float totalAmount = (float) ((0.5)*(totalTimeSpan));
            
            
            String query3 = "update UserDetails set Payment ='"+totalAmount+"' where CarPlateNo ='"+carplateno+"';";
            pst = Home_bookslot.connect().prepareStatement(query3);
            pst.execute(query3);
            
            //String query1 = "update UserHistory set ExitTime1 ='"+ExitTime+"' where carplateno1 ='"+carplateno+"'";
            //pst.execute(query1);
            //String query1 = "insert into UserHistory(Name,MobileNo , CarPlateNo , EntryDate,EntryTime,ExitTime,Payment) select Name,MobileNo , CarPlateNo , EntryDate,EntryTime,ExitTime,Payment from UserDetails;";
            //pst = Home_bookslot.connect().prepareStatement(query1);
            //pst.execute(query1);
            
        }
        catch(SQLException e1){
            e1.printStackTrace();
        }
        
        new Home_Amount().show();

    }//GEN-LAST:event_displayAmountMousePressed

    private void DisplayAmountBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayAmountBtnMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DisplayAmountBtnMousePressed

    private void setTimebtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setTimebtnMousePressed
        String hours = hourchooser.getSelectedItem().toString();
        String mins = minutechooser.getSelectedItem().toString();
        String value = hours + ":" + mins;
        txtexitTime.setText(value);
       
    }//GEN-LAST:event_setTimebtnMousePressed

    private void txtexitTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexitTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtexitTimeActionPerformed

    private void hourchooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourchooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourchooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DisplayAmountBtn;
    private javax.swing.JLabel displayAmount;
    private javax.swing.JComboBox<String> hourchooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> minutechooser;
    private javax.swing.JLabel setTimebtn;
    private com.raven.swing.TimePicker timePicker1;
    public static javax.swing.JTextField txtcarplateno2;
    private javax.swing.JTextField txtexitTime;
    // End of variables declaration//GEN-END:variables
}
