/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.*;
import javax.swing.JOptionPane;
//import static main.Home_viewslot.changeSlotColor();
/**
 *
 * @author Dell
 */
public class Home_bookslot extends javax.swing.JFrame {

    //private String slotname;

    //public String slotname;

    /**
     * Creates new form Home_login
     */
    public Home_bookslot() {
        initComponents();
    }
    
    
    //creating sql connection
    //Connection con;
    PreparedStatement pst;
    public static Connection connect() {
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/minorproject1", "root","Diksha@1503");
            //Statement smt = con.createStatement();
            System.out.println("Connection done successfully");
        }
        catch (ClassNotFoundException ex)
        {
            ex.printStackTrace();

        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
        }
        return con;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timePicker1 = new com.raven.swing.TimePicker();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmobileno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcarplateno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bookbtn = new javax.swing.JPanel();
        bookBtn = new javax.swing.JLabel();
        txtentrydate = new datechooser.beans.DateChooserCombo();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hourchooser1 = new javax.swing.JComboBox<>();
        minutechooser1 = new javax.swing.JComboBox<>();
        setTimebtn1 = new javax.swing.JLabel();
        txtentrytime = new javax.swing.JTextField();

        timePicker1.setForeground(new java.awt.Color(53, 53, 164));
        timePicker1.setDisplayText(txtentrytime);
        timePicker1.setMaximumSize(new java.awt.Dimension(230, 290));
        timePicker1.setMinimumSize(new java.awt.Dimension(230, 290));
        timePicker1.setPreferredSize(new java.awt.Dimension(230, 290));
        timePicker1.getAccessibleContext().setAccessibleName("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(916, 626));

        jPanel1.setBackground(new java.awt.Color(5, 2, 29));
        jPanel1.setMaximumSize(new java.awt.Dimension(913, 626));
        jPanel1.setMinimumSize(new java.awt.Dimension(913, 626));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Enter Details");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Name");

        txtname.setBackground(new java.awt.Color(5, 2, 29));
        txtname.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 255, 204));
        txtname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 12, 58), 2));
        txtname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Mobile no.");

        txtmobileno.setBackground(new java.awt.Color(5, 2, 29));
        txtmobileno.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtmobileno.setForeground(new java.awt.Color(255, 255, 204));
        txtmobileno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtmobileno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 12, 58), 2));
        txtmobileno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtmobileno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobilenoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Car Plate no.");

        txtcarplateno.setBackground(new java.awt.Color(5, 2, 29));
        txtcarplateno.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtcarplateno.setForeground(new java.awt.Color(255, 255, 204));
        txtcarplateno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtcarplateno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 12, 58), 2));
        txtcarplateno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Date");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("Time");

        bookbtn.setBackground(new java.awt.Color(53, 53, 164));
        bookbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 10, 41)));
        bookbtn.setForeground(new java.awt.Color(255, 255, 204));
        bookbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bookBtn.setBackground(new java.awt.Color(17, 12, 58));
        bookBtn.setFont(new java.awt.Font("Century Gothic", 3, 20)); // NOI18N
        bookBtn.setForeground(new java.awt.Color(255, 255, 204));
        bookBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookBtn.setText("Book");
        bookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bookBtnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout bookbtnLayout = new javax.swing.GroupLayout(bookbtn);
        bookbtn.setLayout(bookbtnLayout);
        bookbtnLayout.setHorizontalGroup(
            bookbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );
        bookbtnLayout.setVerticalGroup(
            bookbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtentrydate.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    txtentrydate.setCalendarBackground(new java.awt.Color(5, 2, 29));
    txtentrydate.setFieldFont(new java.awt.Font("Century Gothic", java.awt.Font.BOLD, 12));
    txtentrydate.setNavigateFont(new java.awt.Font("Century Gothic", java.awt.Font.BOLD, 12));
    txtentrydate.setShowOneMonth(true);

    jPanel3.setBackground(new java.awt.Color(53, 53, 164));

    jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 204));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Book Slot");

    jLabel9.setBackground(new java.awt.Color(17, 12, 58));
    jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(255, 255, 204));
    jLabel9.setText("< Back");
    jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            jLabel9MousePressed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel9)
            .addGap(323, 323, 323)
            .addComponent(jLabel1)
            .addContainerGap(405, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel9)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );

    hourchooser1.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
    hourchooser1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " " }));
    hourchooser1.setBorder(null);
    hourchooser1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    hourchooser1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            hourchooser1ActionPerformed(evt);
        }
    });

    minutechooser1.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
    minutechooser1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
    minutechooser1.setBorder(null);
    minutechooser1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    setTimebtn1.setBackground(new java.awt.Color(153, 153, 255));
    setTimebtn1.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
    setTimebtn1.setForeground(new java.awt.Color(255, 255, 204));
    setTimebtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    setTimebtn1.setText("Set Time");
    setTimebtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 12, 58), 2));
    setTimebtn1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            setTimebtn1MousePressed(evt);
        }
    });

    txtentrytime.setBackground(new java.awt.Color(5, 2, 29));
    txtentrytime.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
    txtentrytime.setForeground(new java.awt.Color(255, 255, 204));
    txtentrytime.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    txtentrytime.setText("");
    txtentrytime.setToolTipText("");
    txtentrytime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 12, 58), 2));
    txtentrytime.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7)
                .addComponent(jLabel4)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(hourchooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(minutechooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(setTimebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtmobileno)
                    .addComponent(txtentrydate, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(txtcarplateno)
                    .addComponent(txtname)
                    .addComponent(txtentrytime)))
            .addGap(265, 265, 265))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(388, 388, 388)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(390, 390, 390)
                    .addComponent(bookbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel2)
            .addGap(49, 49, 49)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(txtmobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtcarplateno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtentrydate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtentrytime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(hourchooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(minutechooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(setTimebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(54, 54, 54)
            .addComponent(bookbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(64, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmobilenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobilenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobilenoActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed

        new Home().show();
        
    }//GEN-LAST:event_jLabel9MousePressed
    
    
    public void book(){
        
                String name, mobileno, carplateno, entrydate, entrytime;
                
                //id = txtid.getText();
                name = txtname.getText();
                mobileno = txtmobileno.getText();
                carplateno = txtcarplateno.getText();
                entrydate = txtentrydate.getText();
                entrytime = txtentrytime.getText(); 
                
                
                PriorityQueue<Integer> pq = new PriorityQueue<>();
                String slotname ="";
                String s = "";
                
                
                try {
                    //for adding data in table UserDetails
                    String query = "insert into UserDetails(Name,MobileNo,CarPlateNo,EntryDate,EntryTime,ExitTime,Payment)values(?,?,?,?,?,?,?)";
                    pst = Home_bookslot.connect().prepareStatement(query);
                    
                    //pst = con.prepareStatement(query);
                    //pst.setString(1, id);
                    pst.setString(1, name);
                    pst.setString(2, mobileno);
                    pst.setString(3, carplateno);
                    pst.setString(4, entrydate);
                    pst.setString(5, entrytime);
                    pst.setString(6,null);
                    pst.setString(7, null);

                    pst.executeUpdate();
                    txtname.setText("");
                    txtmobileno.setText("");
                    //txtcarplateno.setText("");
                    txtentrytime.setText("");
                    txtentrydate.setText("");
                    txtcarplateno.requestFocus();
                    
                    
                    //for fetching optimal slot from the table Slots
                    
                    String query2 = "select Distance from Slots where SlotNo is null";
                    pst = Home_bookslot.connect().prepareStatement(query2);
                    ResultSet rs1 = pst.executeQuery(query2);
                    ResultSetMetaData rsmd = rs1.getMetaData();
                    int columnsNumber = rsmd.getColumnCount();
                    while (rs1.next()) {
                        for (int i = 1; i <= columnsNumber; i++) {
                            if (i > 1) System.out.print(",  ");
                            Integer columnValue = rs1.getInt(i);
                            //int value = Integer.parseInt(columnValue); 
                            //System.out.print(columnValue);
                            pq.add(columnValue);
                            
                        }
                        System.out.println("");
                    }
                    /*while (!pq.isEmpty()) {
                        Integer i = pq.poll();
                        System.out.println(i);
                    }*/
                    int dist = pq.peek();
                    ResultSet rs2 = pst.executeQuery("select SlotName from Slots where Distance='"+dist+"' and SlotNo is null");
                    while(rs2.next()){
                         slotname = rs2.getString("SlotName");
                    }
                    System.out.println("Your slot distance is : "+ dist);
                    System.out.println("Your slotname is : "+ slotname);
                    
                    s = slotname.replace("s", "");
                    int slot = Integer.parseInt(s);
                    System.out.println(slot);
                    
                    //update slotno from null to some value
                    
                    String query3 = "update Slots set SlotNo='"+slot+"' where SlotName='"+slotname+"'";
                    pst.execute(query3); 
                    
                    String q01 = "set foreign_key_checks=0";
                    pst.execute(q01);
                    String query4 = "update Slots set CarPlateNo='"+carplateno+"' where SlotName='"+slotname+"'";
                    pst.execute(query4);
                    String q11 = "set foreign_key_checks=1";
                    pst.execute(q11);
            
                } 
                catch (SQLException e1) {
                    e1.printStackTrace();
                }// TODO add your handling code here:
                
                
                String msg = "Your Slotno. is: " + s;
                JOptionPane.showMessageDialog(null, msg );
                
    }
    
    
    private void bookBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookBtnMousePressed
                book();
                new Home_slotdirection().show();
                //obj.changeSlotColor();
    }//GEN-LAST:event_bookBtnMousePressed

    private void hourchooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourchooser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourchooser1ActionPerformed

    private void setTimebtn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setTimebtn1MousePressed
        String hours = hourchooser1.getSelectedItem().toString();
        String mins = minutechooser1.getSelectedItem().toString();
        String value = hours + ":" + mins;
        txtentrytime.setText(value);

    }//GEN-LAST:event_setTimebtn1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_bookslot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_bookslot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_bookslot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_bookslot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_bookslot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel bookBtn;
    public static javax.swing.JPanel bookbtn;
    private javax.swing.JComboBox<String> hourchooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> minutechooser1;
    private javax.swing.JLabel setTimebtn1;
    private com.raven.swing.TimePicker timePicker1;
    public static javax.swing.JTextField txtcarplateno;
    private datechooser.beans.DateChooserCombo txtentrydate;
    public static javax.swing.JTextField txtentrytime;
    private javax.swing.JTextField txtmobileno;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
